---
name: "Docker & Machine"

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker:
    name: "Run on a Docker container"
    runs-on: ubuntu-20.04
    # This is the same image being used in CircleCI
    container: circleci/golang:1.13-buster-node-browsers-legacy
    steps:
      - run: echo "hello, world!"
  machine:
    name: "Run on a (Github hosted) machine"
    runs-on: ubuntu-20.04
    steps:
      # Run on Ubuntu 20.04
      - uses: actions/checkout@v2
      - run: echo "hello, world!"
      # Pull and run a container
      - run: docker run hello-world
