---
name: "Scheduled Jobs"

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  hourly:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "hello, world!"
