---
name: "PoC CircleCI: xwmf"

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 * * * *"
  pull_request:
    branches: master
    # only:
    #   branches: master

jobs:
  hourly_xwfm:
    runs-on: ubuntu-16.04
    steps:
      # TODO: Slack notifications managed through GH
      - uses: actions/checkout@v2
      - name: Loading openvswitch kernel module
        run: sudo modprobe openvswitch
      - name: Setup Environment Variables
        run: |
          echo "MAGMA_ROOT=${PWD}" >> $GITHUB_ENV
          echo "RUN_UID=$RANDOM" >> $GITHUB_ENV
      - name: Login to Artifactory package registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.XWF_ARTIFACTORY_LINK }}
          username: ${{ secrets.XWF_ARTIFACTORY_USER }}
          password: ${{ secrets.XWF_ARTIFACTORY_API_KEY }}
      - run: |
          cd ${MAGMA_ROOT}/xwf/docker/
          docker-compose build --pull --parallel
          docker-compose up -d
          docker exec tests pytest --log-cli-level=info code/tests.py
