---
name: "Virtual Machines & Custom Sizes"

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - master

jobs:
  # virt-virtualbox:
  #   name: "Spin up a virtual machine (virtualbox)"
  #   # Catalina 10.15
  #   # Comes pre-installed with packer, virtualbox, and vagrant
  #   runs-on: macos-latest
  #   steps:
  #     - run: |
  #           mkdir vbox && cd vbox
  #           vagrant init hashicorp/bionic64
  #           vagrant up
  #           vagrant destroy -f
  virt-libvirt:
    name: "Spin up a virtual machine (libvirt)"
    # Catalina 10.15
    # Comes pre-installed with packer, virtualbox, and vagrant
    runs-on: macos-latest
    steps:
      - name: Install and start libvirt from Brew
        run: |
            brew install qemu libvirt
            # brew tap jeffreywildman/homebrew-virt-manager
            # brew install virt-manager virt-viewer
            brew services start libvirt
            # Verify libvirt is up
            #echo "quit" | virsh -c qemu:///session
      - name: Debug libvirt install
        run: |
            virsh list --all
            ls $HOME/.cache/libvirt/
      - name: Install Vagrant Libvirt Plugin
        run: vagrant plugin install vagrant-libvirt
      - run: |
            mkdir libvirt && cd libvirt

            cat > Vagrantfile <<EOL
            Vagrant.configure("2") do |config|
              config.vm.box = "centos/7"
              config.vm.provider :libvirt do |libvirt|
                libvirt.socket = "$HOME/.cache/libvirt/libvirt-sock"
                libvirt.uri = "qemu:///session"
              end
            end
            EOL

            vagrant up --provider libvirt
            vagrant destroy -f
  # custom-size:
  #   # These are not available yet.
  #   name: "Run on a custom instance size"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: false
