---
name: "Virtual Machines & Custom Sizes"

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - master

jobs:
  virt:
    name: "Spin up a virtual machine"
    # Catalina 10.15
    # Comes pre-installed with packer, virtualbox, and vagrant
    runs-on: macos-latest
    steps:
      - name: Run Vagrant Up (virtualbox)
        run: |
            mkdir vbox && cd vbox
            vagrant init hashicorp/bionic64
            vagrant up && vagrant destroy
      - name: Run Vagrant Up (libvirt)
        run: |
            mkdir libvirt && cd libvirt
            vagrant init centos/7
            vagrant up --provider libvirt && vagrant destroy
  custom-size:
    # These are not available yet.
    name: "Run on a custom instance size"
    runs-on: ubuntu-latest
    steps:
      - run: false
